index:
    path: /
    controller: App\Controller\ForumController::index
subforum:
    path: /forum
    controller: App\Controller\ForumController::subforum
thread:
    path: /forum
    controller: App\Controller\ForumController::thread
logout:
    path: /logout
    methods: GET
login:
    path: /login
    controller: App\Controller\LoginController::login
register:
    path: /register
    controller: App\Controller\RegistrationController::register
