index:
    path: /
    controller: App\Controller\ForumController::index
subforum:
    path: /forum
    controller: App\Controller\ForumController::subforum
thread:
    path: /forum
    controller: App\Controller\ForumController::thread
logout:
    path: /logout

app_login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: GET|POST

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: GET|POST
view_profile:
    path: /profile
    controller: App\Controller\ProfileController::index
